services:
  laravel_app:
    build: .
    container_name: laravel_container
    restart: unless-stopped
    ports:
      - "8000:4000"
    depends_on:
      - mysql_db
    volumes:
      - .:/var/www
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  mysql_db:
    image: mysql
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    
volumes:
  mysql_data:
